### ISSUE TITLE
i2c support

### ISSUE THREAD

**Issue by Norr** [rdagger/micropython-ssd1309#4]
This library dosen't have i2c support.

**Comment by rdagger** [comment]
If you look through the closed issues, you'll see some untested code for i2c.

**Comment by rdagger** [comment]
I added I2C support.

**Comment by jjg447** [comment]
I am trying to work this with I2C protocol on a Raspberry Pi Pico using Micropython. I am not having any luck. The error I keep getting is: 

Traceback (most recent call last):
  File "<stdin>", line 40, in <module>
  File "<stdin>", line 12, in test
  File "ssd1309.py", line 124, in __init__
  File "ssd1309.py", line 871, in write_cmd_i2c
OSError: [Errno 5] EIO

**Comment by rdagger** [comment]
Did you set the resistors on the SDD1309 to enable I2C mode?
